version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  node:
    build: ./node
    depends_on:
      - db
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - node
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
