version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: full_cycle
    ports:
      - "3306:3306"

  node:
    build: ./node
    ports:
      - "8080:3000"
    depends_on:
      - db
    volumes:
      - ./node:/app
      - /app/node_modules

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node
